# Generated by Django 5.0.6 on 2024-07-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
